obj-$(CONFIG_PLATFORM_OCTOPUS)	+= eeprom.o
obj-$(CONFIG_PLATFORM_OCTOPUS)	+= memory.o
obj-$(CONFIG_PLATFORM_OCTOPUS)	+= nvram.o
obj-$(CONFIG_PLATFORM_OCTOPUS)	+= sys.o
obj-$(CONFIG_PLATFORM_OCTOPUS)	+= octopus.o
