obj-$(CONFIG_PLATFORM_KAHLEE)	+= eeprom.o
obj-$(CONFIG_PLATFORM_KAHLEE)	+= memory.o
obj-$(CONFIG_PLATFORM_KAHLEE)	+= nvram.o
obj-$(CONFIG_PLATFORM_KAHLEE)	+= sys.o
obj-$(CONFIG_PLATFORM_KAHLEE)	+= kahlee.o
